### ISSUE TITLE
Error in build bij v1.3.1

### ISSUE THREAD

**Issue by sgort** [OpenCatalogi/publiccode-action#6]
Krijg onderstaande errormelding uitvoeren [versie 1.3.1](https://github.com/MinBZK/regels.overheid.nl/commit/1389d6d27525f67fd3a001482efce3de6ba2a84a) in laatste [action run](https://github.com/MinBZK/regels.overheid.nl/actions/runs/7288599242)

```
Run echo "REPO_NAME=regels.overheid.nl" >> $GITHUB_ENV
Installing PyYAML...
Collecting PyYAML
  Downloading PyYAML-6.0.1-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (2.1 kB)
Downloading PyYAML-6.0.1-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (724 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 725.0/725.0 kB 9.0 MB/s eta 0:00:00
Installing collected packages: PyYAML
Successfully installed PyYAML-6.0.1
Run python - <<END
  File "<stdin>", line 22
    with open("publiccode.yml", "r" as f:
                                    ^^
SyntaxError: invalid syntax
Error: Process completed with exit code 1.
```

**Comment by MWest2020** [comment]
Gezien en wordt opgepakt. @sgort . Ik zie hem zelf al. Mist een `)`

**Comment by rjzondervan** [comment]
Zou gefixt moeten zijn in versie 1.3.2

**Comment by MWest2020** [comment]
kun je de workflow nogmaals triggeren @sgort? Dan sluit ik dit issue

**Comment by sgort** [comment]
Fixed indeed.
![image](https://github.com/OpenCatalogi/publiccode-action/assets/25812095/e889b6a7-f1cd-4f85-9ea3-e60cacb7f1f1)
